services:
  grafana:
    image: grafana/grafana:latest
    container_name: nyc_taxi_grafana
    ports:
      - "3001:3000"  
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_storage:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana_storage: